AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy Client API Lambda using Cloudformation.
Resources:
  ReadConfig:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/client-lambda.jar
      Handler: 'at.madlmayr.ReadConfig::handleRequest'
      Runtime: java8
      Description: "Client API Lambda"
      MemorySize: 256
      Timeout: 600 # 10 (!) Minutes Timeout for Testing Purpose.
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: ReadConfig
      Tracing: Active
  SlackCall:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/client-lambda.jar
      Handler: 'at.madlmayr.slack.SlackCall::handleRequest'
      Runtime: java8
      Description: "Slack Call"
      MemorySize: 256
      Timeout: 60
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: SlackCall
      Tracing: Active
  ArtifactoryCall:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/client-lambda.jar
      Handler: 'at.madlmayr.artifactory.ArtifactoryCall::handleRequest'
      Runtime: java8
      Description: "Artifactory Call"
      MemorySize: 256
      Timeout: 60
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: ArtifactoryCall
      Tracing: Active
  JiraV2Call:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/client-lambda.jar
      Handler: 'at.madlmayr.jira.JiraV2Call::handleRequest'
      Runtime: java8
      Description: "JiraV2Call Call"
      MemorySize: 256
      Timeout: 180
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: JiraV2Call
      Tracing: Active
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: FirehoseFullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - firehose:*
                  - xray:*
                  - dynamodb:*
                  - lambda:InvokeFunction
                Resource: "*"
  RateRuleDaily:
    Type: AWS::Events::Rule
    Properties:
      Description: "Run Event every Minute"
      Name: "RateRuleDaily"
      ScheduleExpression: rate(1 minute)
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt
            - ReadConfig
            - Arn
          Id: RateRuleDailyScheduler
          # Input: "Input"
          #RoleArn: !GetAtt
          #  - EventsInvokeKinesisTargetRole
          #  - Arn
  InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ReadConfig.Arn
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt RateRuleDaily.Arn
  DynamoDBConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "company"
          AttributeType: "S"
        - AttributeName: "tool"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "company"
          KeyType: "HASH"
        - AttributeName: "tool"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: "Config"
  DynamoDBAccountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "companyToolTimestamp"
          AttributeType: "S"
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "companyToolTimestamp"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "Accounts"
Outputs:
  TableName:
    Value: !Ref 'DynamoDBConfigTable'
    Description: Table name of the newly created DynamoDB table for Configs