AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy Client API Lambda using Cloudformation.
Resources:
  ClientApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/client-lambda.jar
      Handler: 'at.madlmayr.SampleLambda::handleRequest'
      Runtime: java8
      Description: "Client API Lambda"
      MemorySize: 512
      Timeout: 15
      Role: !GetAtt LambdaExecutionRole.Arn
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: FirehoseFullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - firehose:*
                  - xray:*
                Resource: "*"
  RateRuleDaily:
    Type: AWS::Events::Rule
    Properties:
      Description: "Run Event every Minute"
      Name: "RateRuleDaily"
      ScheduleExpression: cron(* * * * ? *)
      State: "ENABLED"
      EventPattern: "Static Input for Lambda"
      Targets:
        - Arn: !GetAtt
            - ClientApi
            - Arn
          Id: RateRuleDailyScheduler
          #RoleArn: !GetAtt
          #  - EventsInvokeKinesisTargetRole
          #  - Arn
  InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ClientApi.Arn
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt RateRuleDaily.Arn
